In [ ]:
import pandas as pd
import os

auction = pd.read_excel("/content/Auction.xlsx")
batsmen = pd.read_excel("/content/Top_100_batsman.xlsx")
bowlers = pd.read_excel("/content/Top_100_bowlers.xlsx")
matches = pd.read_csv("/content/matches.csv")

print("All four datasets loaded successfully!")

All four datasets loaded successfully!

In [ ]:
datasets = {
      "Auction": auction,
      "Top 100 Batsmen": batsmen,
      "Top 100 Bowlers": bowlers,
      "IPL Matches": matches
 }

for name, data in datasets.items():
    print("\n" + "=" * 50)
    print("DATASET:", name)
    print("Shape (Rows, Columns):", data.shape)
    print("\nColumn Names:")
    print(data.columns.tolist())
    print("\nFirst 5 Rows:")
    display(data.head())

==================================================
DATASET: Auction
Shape (Rows, Columns): (56, 5)

Column Names:
['TEAM', 'PLAYER', 'TYPE', 'PRICE(In crore Indian Rupees) ', 'YEAR']

First 5 Rows:

,TEAM,PLAYER,TYPE,PRICE(In crore Indian Rupees),YEAR
0,Kolkata Knight Riders,Pat Cummins,All-Rounder,15.50,2020
1,Kings XI Punjab,Glenn Maxwell,All-Rounder,10.75,2020
2,Royal Challengers Bangalore,Christopher Morris,All-Rounder,10.00,2020
3,Kings XI Punjab,Sheldon Cottrell,Bowler,8.50,2020
4,Mumbai Indians,Nathan Coulter-Nile,Bowler,8.00,2020

==================================================
DATASET: Top 100 Batsmen
Shape (Rows, Columns): (100, 14)

Column Names:
['POS', 'PLAYER', 'Mat', 'Inns', 'NO', 'Runs', 'HS', 'Avg', 'BF', 'SR', 100, 50, '4s', '6s']

First 5 Rows:

,POS,PLAYER,Mat,Inns,NO,Runs,HS,Avg,BF,SR,100,50,4s,6s
0,1,ViratKohli,177,169,26,5412,113,37.84,4112,131.61,5,36,480,190
1,2,Suresh Raina,193,189,28,5368,100*,33.34,3914,137.14,1,38,493,194
2,3,Rohit Sharma,188,183,28,4898,109*,31.60,3744,130.82,1,36,431,194
3,4,David Warner,126,126,17,4706,126,43.17,3305,142.39,4,44,458,181
4,5,Shikhar Dhawan,159,158,21,4579,97*,33.42,3669,124.80,0,37,524,96

==================================================
DATASET: Top 100 Bowlers
Shape (Rows, Columns): (100, 13)

Column Names:
['POS', 'PLAYER', 'Mat', 'Inns', 'Ov', 'Runs', 'Wkts', 'BBI', 'Avg', 'Econ', 'SR', '4w', '5w']

First 5 Rows:

,POS,PLAYER,Mat,Inns,Ov,Runs,Wkts,BBI,Avg,Econ,SR,4w,5w
0,1,LasithMalinga,122,122,471.1,3366,170,0,19.80,7.14,16.62,6,1
1,2,Amit Mishra,147,147,516.5,3799,157,0,24.19,7.35,19.75,3,1
2,3,Harbhajan Singh,160,157,562.2,3967,150,0,26.44,7.05,22.49,1,1
3,4,Piyush Chawla,157,156,520.4,4072,150,0,27.14,7.82,20.82,2,0
4,5,Dwayne Bravo,134,131,431.0,3617,147,0,24.60,8.39,17.59,2,0

==================================================
DATASET: IPL Matches
Shape (Rows, Columns): (756, 18)

Column Names:
['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner', 'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs', 'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2', 'umpire3']

First 5 Rows:

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,4/5/2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,4/6/2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,4/7/2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,4/8/2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,4/8/2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [ ]:
for name, data in datasets.items():
    print("\n" + "=" * 50)
    print("DATASET:", name)
    print("Rows and Columns:", data.shape)

    print("\nMissing Values:")
    print(data.isnull().sum())

    print("\nDuplicate Rows:")
    print(data.duplicated().sum())

    print("\nData Types:")
    print(data.dtypes)

==================================================
DATASET: Auction
Rows and Columns: (56, 5)

Missing Values:
TEAM                              0
PLAYER                            0
TYPE                              0
PRICE(In crore Indian Rupees)     0
YEAR                              0
dtype: int64

Duplicate Rows:
0

Data Types:
TEAM                               object
PLAYER                             object
TYPE                               object
PRICE(In crore Indian Rupees)     float64
YEAR                                int64
dtype: object

==================================================
DATASET: Top 100 Batsmen
Rows and Columns: (100, 14)

Missing Values:
POS       0
PLAYER    0
Mat       0
Inns      0
NO        0
Runs      0
HS        0
Avg       0
BF        0
SR        0
100       0
50        0
4s        0
6s        0
dtype: int64

Duplicate Rows:
0

Data Types:
POS         int64
PLAYER     object
Mat         int64
Inns        int64
NO          int64
Runs        int64
HS         object
Avg       float64
BF          int64
SR        float64
100         int64
50          int64
4s          int64
6s          int64
dtype: object

==================================================
DATASET: Top 100 Bowlers
Rows and Columns: (100, 13)

Missing Values:
POS       0
PLAYER    0
Mat       0
Inns      0
Ov        0
Runs      0
Wkts      0
BBI       0
Avg       0
Econ      0
SR        0
4w        0
5w        0
dtype: int64

Duplicate Rows:
0

Data Types:
POS         int64
PLAYER     object
Mat         int64
Inns        int64
Ov        float64
Runs        int64
Wkts        int64
BBI         int64
Avg       float64
Econ      float64
SR        float64
4w          int64
5w          int64
dtype: object

==================================================
DATASET: IPL Matches
Rows and Columns: (756, 18)

Missing Values:
id                   0
season               0
city                 7
date                 0
team1                0
team2                0
toss_winner          0
toss_decision        0
result               0
dl_applied           0
winner               4
win_by_runs          0
win_by_wickets       0
player_of_match      4
venue                0
umpire1              2
umpire2              2
umpire3            637
dtype: int64

Duplicate Rows:
0

Data Types:
id                  int64
season              int64
city               object
date               object
team1              object
team2              object
toss_winner        object
toss_decision      object
result             object
dl_applied          int64
winner             object
win_by_runs         int64
win_by_wickets      int64
player_of_match    object
venue              object
umpire1            object
umpire2            object
umpire3            object
dtype: object

In [ ]:
# Week 1: Summary Statistics

print("AUCTION PRICE SUMMARY")
display(auction.describe())

print("\nTOP BATSMEN PERFORMANCE SUMMARY")
display(batsmen.describe())

print("\nTOP BOWLERS PERFORMANCE SUMMARY")
display(bowlers.describe())

print("\nIPL MATCHES SUMMARY")
display(matches.describe())

AUCTION PRICE SUMMARY

       PRICE(In crore Indian Rupees)        YEAR
count                       56.000000    56.0000
mean                         7.636607  2017.0000
std                          3.295155     2.0181
min                          3.000000  2014.0000
25%                          5.000000  2015.0000
50%                          7.000000  2017.0000
75%                          9.525000  2019.0000
max                         16.000000  2020.0000

TOP BATSMEN PERFORMANCE SUMMARY

,POS,Mat,Inns,NO,Runs,Avg,BF,SR,100,50,4s,6s
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,50.500000,85.130000,76.630000,14.050000,1828.820000,28.559500,1398.490000,130.745000,0.560000,10.360000,170.280000,68.380000
std,29.011492,46.042066,41.753402,11.666558,1231.417434,6.615644,920.376246,13.028519,1.094707,9.594316,121.580341,55.246332
min,1.000000,16.000000,16.000000,0.000000,531.000000,11.910000,407.000000,106.800000,0.000000,0.000000,34.000000,9.000000
25%,25.750000,49.000000,45.000000,5.000000,938.250000,23.902500,704.250000,122.625000,0.000000,4.000000,82.000000,34.000000
50%,50.500000,76.000000,67.500000,11.000000,1420.500000,28.185000,1113.500000,128.895000,0.000000,8.000000,127.000000,46.500000
75%,75.250000,110.750000,95.250000,21.000000,2346.750000,33.030000,1789.500000,137.360000,1.000000,13.000000,240.000000,82.500000
max,100.000000,193.000000,189.000000,65.000000,5412.000000,44.380000,4112.000000,186.410000,6.000000,44.000000,524.000000,326.000000

TOP BOWLERS PERFORMANCE SUMMARY

,POS,Mat,Inns,Ov,Runs,Wkts,BBI,Avg,Econ,SR,4w,5w
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.0,100.0000,100.000000,100.000000,100.000000,100.000000
mean,50.500000,68.350000,62.970000,213.756000,1665.650000,60.590000,0.0,28.3890,7.865800,21.684600,0.900000,0.150000
std,29.011492,40.027106,33.354677,117.314975,873.251041,34.814398,0.0,5.6535,0.637673,4.241365,1.141504,0.411329
min,1.000000,18.000000,18.000000,68.200000,520.000000,25.000000,0.0,17.9300,6.550000,13.220000,0.000000,0.000000
25%,25.750000,37.750000,37.750000,127.075000,1038.500000,34.000000,0.0,24.6975,7.415000,19.367500,0.000000,0.000000
50%,50.500000,56.500000,55.000000,176.800000,1401.500000,45.000000,0.0,27.9250,7.830000,21.005000,1.000000,0.000000
75%,75.250000,90.250000,82.250000,288.250000,2277.250000,79.250000,0.0,30.5875,8.307500,23.115000,1.000000,0.000000
max,100.000000,193.000000,157.000000,562.200000,4072.000000,170.000000,0.0,46.1700,9.200000,37.060000,6.000000,2.000000

IPL MATCHES SUMMARY

                 id       season  dl_applied  win_by_runs  win_by_wickets
count    756.000000   756.000000  756.000000   756.000000      756.000000
mean    1792.178571  2013.444444    0.025132    13.283069        3.350529
std     3464.478148     3.366895    0.156630    23.471144        3.387963
min        1.000000  2008.000000    0.000000     0.000000        0.000000
25%      189.750000  2011.000000    0.000000     0.000000        0.000000
50%      378.500000  2013.000000    0.000000     0.000000        4.000000
75%      567.250000  2016.000000    0.000000    19.000000        6.000000
max    11415.000000  2019.000000    1.000000   146.000000       10.000000

In [15]:
print("TOP 5 MOST EXPENSIVE PLAYERS IN AUCTION")

print(auction.sort_values(
    by="PRICE(In crore Indian Rupees) ",
        ascending=False
        ).head(5))
print("\nTOP 5 BATSMEN BY RUNS")

print(batsmen.sort_values(
      by="Runs",
          ascending=False
          )[["PLAYER", "Runs"]].head(5))
print("\nTOP 5 BOWLERS BY WICKETS")

print(bowlers.sort_values(
    by="Wkts",
        ascending=False
)[["PLAYER", "Wkts"]].head(5))

TOP 5 MOST EXPENSIVE PLAYERS IN AUCTION
                            TEAM           PLAYER           TYPE  \
40              Delhi Daredevils     Yuvraj Singh        Batsman
0          Kolkata Knight Riders      Pat Cummins    All-Rounder
24        Rising Pune Supergiant  Benjamin Stokes    All-Rounder
48   Royal Challengers Bangalore     Yuvraj Singh    All-Rounder
49              Delhi Daredevils   Dinesh Karthik  Wicket Keeper

    PRICE(In crore Indian Rupees)   YEAR
40                            16.0  2015
0                             15.5  2020
24                            14.5  2017
48                            14.0  2014
49                            12.5  2014

TOP 5 BATSMEN BY RUNS
           PLAYER  Runs
0      ViratKohli  5412
1    Suresh Raina  5368
2    Rohit Sharma  4898
3    David Warner  4706
4  Shikhar Dhawan  4579

TOP 5 BOWLERS BY WICKETS
            PLAYER  Wkts
0    LasithMalinga   170
1      Amit Mishra   157
2  Harbhajan Singh   150
3    Piyush Chawla   150
4     Dwayne Bravo   147

In [16]:
# Week 1: IPL Team Performance Analysis

print("TOP 10 TEAMS BY MATCH WINS")

team_wins = matches["winner"].value_counts().head(10)

print(team_wins)

print("\nMOST SUCCESSFUL TEAM")

print("Team:", team_wins.index[0])
print("Total Wins:", team_wins.iloc[0])

TOP 10 TEAMS BY MATCH WINS
winner
Mumbai Indians                 109
Chennai Super Kings            100
Kolkata Knight Riders           92
Royal Challengers Bangalore     84
Kings XI Punjab                 82
Rajasthan Royals                75
Delhi Daredevils                67
Sunrisers Hyderabad             58
Deccan Chargers                 29
Rising Pune Supergiant          15
Name: count, dtype: int64

MOST SUCCESSFUL TEAM
Team: Mumbai Indians
Total Wins: 109